BorderForce\Drt\EntityBundle\Entity\ArchyTypePriority:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\ArchyTypePriorityRepository
  table: archy_type_priority
  id:
    id:
      type: integer
      length: 2
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(30), nullable: false }
  uniqueConstraints:
    uniquePriorityName:
      columns: [name]