BorderForce\Drt\EntityBundle\Entity\ArchyTypeClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\ArchyTypeRepository
  table: archy_type_class
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(30), nullable: false }
  manyToOne:
    PriorityType:
      targetEntity: ArchyTypePriority
      inversedBy: ArchyType
      joinColumn:
        name: archy_type_priority_id
        referencedColumnName: id