BorderForce\Drt\EntityBundle\Entity\CarrierDetails:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\CarrierDetailsRepository
  table: carrier_details
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    code:  { type: string(10), nullable: false }
    paxOffRate: { type: integer(8), nullable: true, name: pax_off_rate }
    carrierCapacity: { type: integer(8), nullable: true, name: carrier_capacity }
    firstPaxOffTime: { type: integer(8), nullable: true, name: first_pax_off_time }
    avgWalkTime: { type: integer(8), nullable: true, name: avg_walk_time }
    avgWalkTimeDateTime: { type: datetime, nullable: true }
    avgChoxTime: { type: integer(8), nullable: true, name: avg_chox_time }
    avgChoxTimeDateTime: { type: datetime, nullable: true }
  uniqueConstraints:
    uniqueCarrierCodeType:
      columns: [code,carrier_type_id]
    uniqueCarrierOperatorCode:
      columns: [code,operator_id]
  manyToOne:
    LocalPort:
      targetEntity: Port
      inversedBy: Carrier
      joinColumn:
        name: local_port_id
        referencedColumnName: id
    OriginPort:
      targetEntity: BasePort
      inversedBy: Carrier
      joinColumn:
        name: origin_port_id
        referencedColumnName: id
    CarrierType:
      targetEntity: CarrierType
      inversedBy: Carrier
      joinColumn:
        name: carrier_type_id
        referencedColumnName: id
    Operator:
      targetEntity: Operator
      inversedBy: CarrierDetails
      joinColumn:
        name: operator_id
        referencedColumnName: id
#Timestampable, blameable, softdelete