BorderForce\Drt\EntityBundle\Entity\CarrierSplitTimeParam:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\CarrierSplitTimeParamRepository
  table: carrier_split_time_param
  manyToOne:
    CarrierPaxSplit:
      targetEntity: CarrierPaxSplit
      inversedBy: ParamSplitTime
      joinColumn:
        name: carrier_pax_split_time_id
        referencedColumnName: id
    PaxSplitClass:
      targetEntity: PaxSplitClass
      inversedBy: PaxSplitTimeClass
      joinColumn:
        name: pax_split_time_class_id
        referencedColumnName: id