BorderForce\Drt\EntityBundle\Entity\CarrierType:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\CarrierTypeRepository
  table: carrier_type
  id:
    id:
      type: integer
      length: 2
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(50), nullable: false }
  uniqueConstraints:
    uniqueCarrierTypeName:
      columns: [name]