BorderForce\Drt\EntityBundle\Entity\CarrierSplitTimeParam:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\CarrierSplitTimeParamRepository
  table: carrier_split_time_param
#  attributeOverride:
#    DayOfWeek:  { type: string(10), nullable: false, name: day_of_week }
#    MonthOfYear:  { type: string(10), nullable: false, name: month_of_year }
  manyToOne:
    CarrierDetails:
      targetEntity: CarrierDetails
      inversedBy: ParamSplitTime
      joinColumn:
        name: carrier_split_time_id
        referencedColumnName: id
    PaxSplitClass:
      targetEntity: PaxSplitClass
      inversedBy: PaxSplitTimeClass
      joinColumn:
        name: pax_split_time_class_id
        referencedColumnName: id