BorderForce\Drt\EntityBundle\Entity\CarrierPaxSplit:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\CarrierPaxSplit
  table: carrier_pax_split
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    active: { type: boolean, nullable: false }
  manyToOne:
    CarrierDetails:
      targetEntity: CarrierDetails
      inversedBy: CarrierDetailsPaxSplit
      joinColumn:
        name: carrier_details_id
        referencedColumnName: id
    PaxSplitClass:
      targetEntity: PaxSplitClass
      inversedBy: CarrierDetailsPaxSplit
      joinColumn:
        name: pax_split_id
        referencedColumnName: id
  uniqueConstraints:
    uniquePortTermCode:
      columns: [carrier_details_id,pax_split_id]
#Timestampable, blameable, softdelete