BorderForce\Drt\EntityBundle\Entity\FixedPointType:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\FixedPointRepository
  table: fixed_point
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(10), nullable: false }
  uniqueConstraints:
    uniqueTermFP:
      columns: [name]