BorderForce\Drt\EntityBundle\Entity\Operator:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\OperatorRepository
  table: operator
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    code:  { type: string(10), nullable: false }
    name:  { type: string(100), nullable: false }