BorderForce\Drt\EntityBundle\Entity\PaxCategoryClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\PaxCategoryRepository
  table: paxcategory
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    symbol:  { type: string(5), nullable: false }
    name:  { type: string(30), nullable: false }
#  manyToOne:
#    port:
#      targetEntity: Port
#      inversedBy: PaxCategories
#      joinColumn:
#        name: port_id
#        referencedColumnName: id
  uniqueConstraints:
    uniqueCategoryName:
      columns: [name]
    uniqueCategorySymbol:
      columns: [symbol]
#Timestampable, blameable, softdelete