BorderForce\Drt\EntityBundle\Entity\PaxSplitClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\PaxSplitClassRepository
  table: paxsplit
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    symbol:  { type: string(5), nullable: false }
    name:  { type: string(50), nullable: false }
#  ManyToOne:
#    port:
#      targetEntity: Port
#      inversedBy: PaxSplits
#      joinColumn:
#        name: port_id
#        referencedColumnName: id
  uniqueConstraints:
    uniquePaxSplitName:
      columns: [name]
    uniquePaxSplitSymbol:
      columns: [symbol]
#Timestampable, blameable, softdelete