BorderForce\Drt\EntityBundle\Entity\PortType:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\PortTypeRepository
  table: port_type
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(50), nullable: false }
  uniqueConstraints:
    uniquePortTypeName:
      columns: [name]