BorderForce\Drt\EntityBundle\Entity\ProcessTimeClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\ProcessTimeClassRepository
  table: process_time_class
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(40), nullable: false }
#  ManyToOne:
#    Port:
#      targetEntity: Port
#      inversedBy: port
#      joinColumn:
#        name: port_id
#        referencedColumnName: id
  uniqueConstraints:
    uniqueProcessTime:
      columns: [name]
#Timestampable, blameable, softdelete