BorderForce\Drt\EntityBundle\Entity\QueueClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\QueueClassRepository
  table: queue_class
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    name:  { type: string(10), nullable: false }
    color:  { type: integer(2), nullable: false }
    sla:  { type: integer(8), nullable: true }
    manned:  { type: boolean, nullable: true }
  uniqueConstraints:
    uniqueProcessTime:
      columns: [name]