BorderForce\Drt\EntityBundle\Entity\QueueClass:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\QueueClassRepository
  table: queue
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    queuename:  { type: string(10), nullable: false }
    colorcode:  { type: integer(2), nullable: false }
    thresholdsla:  { type: integer(8), nullable: true }
    staffedqueue:  { type: boolean, nullable: true }
#  ManyToOne:
#    Port:
#      targetEntity: Terminal
#      inversedBy: terminal
#      joinColumn:
#        name: term_id
#        referencedColumnName: id
  uniqueConstraints:
    uniqueProcessTime:
      columns: [queuename]