BorderForce\Drt\EntityBundle\Entity\TerminalQueue:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\TerminalQueueRepository
  table: terminal_queue
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    manned: { type: boolean, nullable: false }
    active: { type: boolean, nullable: false }
    color: { type: string(30), nullable: false }
    sla: { type: integer, nullable: true}
  manyToOne:
    Terminal:
      targetEntity: Terminal
      inversedBy: TerminalQueue
      joinColumn:
        name: terminal_id
        referencedColumnName: id
    QueueClass:
      targetEntity: QueueClass
      inversedBy: TerminalQueue
      joinColumn:
        name: queue_class_id
        referencedColumnName: id
  uniqueConstraints:
    uniquePortTermCode:
      columns: [terminal_id,queue_class_id]
#Timestampable, blameable, softdelete