BorderForce\Drt\EntityBundle\Entity\TerminalSplitTimeParam:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\TerminalSplitTimeParamRepository
  table: terminal_split_time_param
  manyToOne:
    TerminalPaxSplit:
      targetEntity: TerminalPaxSplit
      inversedBy: ParamSplitTime
      joinColumn:
        name: terminal_split_time_id
        referencedColumnName: id
    PaxSplitClass:
      targetEntity: PaxSplitClass
      inversedBy: PaxParamSplitTime
      joinColumn:
        name: pax_split_time_class_id
        referencedColumnName: id