BorderForce\Drt\EntityBundle\Entity\TimeParam:
  type: entity
  repositoryClass: BorderForce\Drt\EntityBundle\Entity\Repository\TimeParamRepository
  table: timeparam
  inheritanceType: JOINED
  discriminatorColumn:
    name: discriminator
    type: string
    length: 255
  discriminatorMap:
    queue: TerminalQueueTimeParam
    fixed_points: TerminalFixedPointParam
    terminal_pt: TerminalProcessingTimeParam
    carrier_pt: CarrierProcessingTimeParam
    terminal_spl: TerminalSplitTimeParam
    carrier_spl: CarrierSplitTimeParam
  id:
    id:
      type: integer
      length: 12
      generator:
        strategy: AUTO
  fields:
    DayOfWeek:  { type: string(10), nullable: true, name: day_of_week }
    MonthOfYear:  { type: string(10), nullable: true, name: month_of_year }
    HourOfDay:  { type: integer(8), nullable: true, name: hour_of_day }
    ParamValue:  { type: integer(10), nullable: false, name: param_value }
    isPercent:  { type: boolean, nullable: false, name: is_percent }
    hasDayOfWeek: { type: boolean, nullable: false, name: has_day_of_week }
    hasMonthOfYear: { type: boolean, nullable: false, name: has_month_of_year }
    hasHourOfDay: { type: boolean, nullable: false, name: has_hour_of_day }
    HourOfDaySlice: { type: integer(2), nullable: true, name: hour_of_day_slice }
  uniqueConstraints:
    singleParamAtTime:
      columns: [discriminator,DayOfWeek, MonthOfYear, HourOfDay]