parameters:
#    border_force_drt_base.example.class: BorderForce\Drt\EntityBundle\Example

services:
#    border_force_drt_base.example:
#        class: %border_force_drt_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
