#parameters:
#    border_force_drt_base.example.class: BorderForce\Drt\EntityBundle\Example

services:
    nested_cascade_create_entity:
        class: BorderForce\Drt\EntityBundle\Form\Type\NestedCascadeCreateEntityType
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer"]
        tags:
            - { name: form.type, alias: nested_cascade_create_entity }
