BorderForce\Drt\EntityBundle\Entity\Flight:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [ flightNumber, scheduledDate ]
        message: "this flight already exists for this day."
  properties:
    flightNumber:
      - NotBlank: ~
    scheduledDate:
      - DateTime: ~
      - NotBlank: ~
    touchdownEstimated:
      - DateTime: ~
    touchdown:
      - DateTime: ~
    choxEstimated:
      - DateTime: ~
    chox:
      - DateTime: ~
    origin:
      - NotBlank: ~
      - Length:
          min: 3
          max: 256
#    airline:
#      - NotBlank: ~
#    passengers:
#      - Type:
#        type: integer
#      - Range: 
#          min: 5
#          max: 700
      
    