<?php

namespace BorderForce\Drt\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActualArrivalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualArrivalsRepository extends EntityRepository
{
}
