<?php

namespace BorderForce\Drt\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightRepository extends EntityRepository
{
  
  public function findByFlightNumberAndScheduledDate($flightNumber, $scheduledDate) {
    
    try {
      $flight = $this->getEntityManager()->createQuery(
        'select f from BorderForceDrtEntityBundle:Flight f
         where f.flightNumber = :flightNumber and
         f.scheduledDate = :scheduledDate')
        ->setParameter('flightNumber',  $flightNumber)
        ->setParameter('scheduledDate', $scheduledDate)
        ->getSingleResult();
    }
    catch (\Doctrine\Orm\NoResultException $e) {
      $flight = null;
    }
    return $flight;
  }
  
  public function findAllOrderedByTouchdownEstimated() {
    
    try {
      $flight = $this->getEntityManager()->createQuery(
        'select f from BorderForceDrtEntityBundle:Flight f
         order by f.touchdownEstimated')
        ->execute();
    }
    catch (\Doctrine\Orm\NoResultException $e) {
      $flight = null;
    }
    return $flight;
  }
  
}
